{{- /* templates/secrets.yaml */}}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  # Use the name defined in values.yaml or generate based on chart fullname
  name: {{ .Values.secrets.name | default (printf "%s-credentials" (include "mautic.fullname" .)) }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Use the password keys defined in values.yaml under mautic.database and mautic.mailer
  {{ .Values.mautic.database.passwordSecretKey }}: {{ .Values.secrets.databasePassword | quote }}
  {{- if .Values.mautic.mailer.passwordSecretKey }} {{- /* Only add mailer password if key is defined */}}
  {{ .Values.mautic.mailer.passwordSecretKey }}: {{ .Values.secrets.mailerPassword | quote }}
  {{- end }}
  # Add any other secret values here if needed
{{- end }} 