create table accounts
(
    id         bigint generated by default as identity not null,
    email      varchar(255),
    password   varchar(255),
    name       varchar(255),
    created_at timestamp without time zone             not null,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    constraint pk_accounts primary key (id)
);

create table chapter_texts
(
    id         bigint generated by default as identity not null,
    account_id bigint                                  not null,
    content    text,
    chapter_id bigint                                  not null,
    created_at timestamp without time zone             not null,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    constraint pk_chapter_texts primary key (id)
);

create table chapters
(
    id          bigint generated by default as identity not null,
    title       varchar(255),
    description text,
    novel_id    bigint                                  not null,
    created_at  timestamp without time zone             not null,
    updated_at  timestamp without time zone,
    deleted_at  timestamp without time zone,
    constraint pk_chapters primary key (id)
);

create table characters
(
    id              bigint generated by default as identity not null,
    name            varchar(255),
    description     text,
    profile_image   varchar(255),
    last_updated_by bigint,
    priority        integer,
    novel_id        bigint                                  not null,
    created_at      timestamp without time zone             not null,
    updated_at      timestamp without time zone,
    deleted_at      timestamp without time zone,
    constraint pk_characters primary key (id)
);

create table contributor_groups
(
    id                    bigint generated by default as identity not null,
    max_contributor_count integer,
    contributor_count     integer,
    status                smallint,
    novel_id              bigint                                  not null,
    completed_at          timestamp without time zone,
    created_at            timestamp without time zone             not null,
    updated_at            timestamp without time zone,
    deleted_at            timestamp without time zone,
    constraint pk_contributor_groups primary key (id)
);

create table contributor_requests
(
    id                   bigint generated by default as identity not null,
    contributor_group_id bigint                                  not null,
    novel_id             bigint                                  not null,
    account_id           bigint                                  not null,
    status               varchar(255),
    created_at           timestamp without time zone             not null,
    updated_at           timestamp without time zone,
    deleted_at           timestamp without time zone,
    constraint pk_contributor_requests primary key (id)
);

create table contributors
(
    id                   bigint generated by default as identity not null,
    account_id           bigint                                  not null,
    role                 varchar(255),
    writing_order        integer,
    contributor_group_id bigint                                  not null,
    created_at           timestamp without time zone             not null,
    updated_at           timestamp without time zone,
    deleted_at           timestamp without time zone,
    constraint pk_contributors primary key (id)
);

create table novel_tags
(
    id         bigint generated by default as identity not null,
    name       varchar(255),
    novel_id   bigint                                  not null,
    created_at timestamp without time zone             not null,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    constraint pk_novel_tags primary key (id)
);

create table novels
(
    id          bigint generated by default as identity not null,
    title       varchar(255),
    description text,
    cover_image varchar(255),
    category    varchar(255),
    synopsis    text,
    created_at  timestamp without time zone             not null,
    updated_at  timestamp without time zone,
    deleted_at  timestamp without time zone,
    constraint pk_novels primary key (id)
);

create index idx_account_email on accounts (email);
